package challenges

const (
	REDIS_CHALLENGES_HASH   = "challenges"
	CHALLENGE_ACCEPT_ACTION = "accept"
	CHALLENGE_DENY_ACTION   = "deny"
	CHALLENGE_CANCEL_ACTION = "cancel"
	DENY_CHALLENGE_EVENT    = "deny:challenge"
	NEW_CHALLENGE_EVENT     = "new:challenge"
	CANCEL_CHALLENGE_EVENT  = "cancel:challenge"
	ACCEPT_CHALLENGE_EVENT  = "accept:challenge"
	SESSION_CREATE_EVENT    = "create:session"
)

var CHALLENGE_ACTION_MAP = map[string]string{CHALLENGE_ACCEPT_ACTION: ACCEPT_CHALLENGE_EVENT, CHALLENGE_DENY_ACTION: DENY_CHALLENGE_EVENT, CHALLENGE_CANCEL_ACTION: CANCEL_CHALLENGE_EVENT}
